import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ConvexClientProvider } from '@/components/providers/ConvexClientProvider';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen relative antialiased`}
      >
        <ConvexClientProvider>
          <div className='absolute top-0 -z-10 h-full w-full bg-white'>
            <div className='absolute bottom-auto left-auto right-0 top-0 h-[500px] w-[500px] -translate-x-[30%] translate-y-[20%] rounded-full bg-[rgba(173,109,244,0.5)] opacity-50 blur-[80px]'></div>
          </div>
          <Navbar />
          {children}
          <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
